# Generated by Django 5.1.4 on 2025-01-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='year',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
