# Generated by Django 5.1.4 on 2025-03-02 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_designation_remove_student_department_batch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='experience',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
