# Generated by Django 5.1.4 on 2025-03-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_teacher_experience'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='middle_name',
        ),
        migrations.AlterField(
            model_name='teacher',
            name='experience',
            field=models.PositiveIntegerField(),
        ),
    ]
