# Generated by Django 5.1.4 on 2025-03-19 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_domain_teacherpreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sem', models.CharField(max_length=50)),
                ('div', models.CharField(max_length=50)),
                ('form', models.IntegerField()),
                ('tech', models.CharField(max_length=100, null=True)),
                ('project_co_coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prj_co_ord', to='api.teacher')),
                ('project_coordinator', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prj_coord', to='api.teacher')),
                ('year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.year')),
            ],
            options={
                'db_table': 'sem',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('final_topic', models.CharField(max_length=1000, null=True)),
                ('leader', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leader_info', to='api.student')),
                ('members', models.ManyToManyField(related_name='member_info', to='api.student')),
                ('project_co_guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prj_co_guide', to='api.teacher')),
                ('project_guide', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prj_guide', to='api.teacher')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sem')),
            ],
            options={
                'db_table': 'project',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.CharField(max_length=1000, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(max_length=100, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.teacher')),
                ('sem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sem')),
            ],
            options={
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='CurrentSem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form', models.IntegerField(default=0)),
                ('info', models.IntegerField(default=0)),
                ('leader', models.IntegerField(default=0)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.student')),
                ('sem', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.sem')),
            ],
            options={
                'db_table': 'currentsem',
            },
        ),
    ]
