# Generated by Django 5.1.4 on 2025-03-22 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_sem_project_notification_currentsem'),
    ]

    operations = [
        migrations.AddField(
            model_name='sem',
            name='class_incharge',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
    ]
