# Generated by Django 5.1.4 on 2025-03-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_sem_class_incharge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sem',
            name='div',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
