# Generated by Django 5.1.4 on 2025-03-23 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_sem_div'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='final_abstract',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='final_topic',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
