# Generated by Django 5.1.4 on 2025-03-23 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_project_final_abstract_alter_project_final_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentsem',
            name='info',
        ),
        migrations.RemoveField(
            model_name='currentsem',
            name='leader',
        ),
    ]
