# Generated by Django 5.1.4 on 2025-03-23 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_currentsem_div'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='currentsem',
            name='div',
        ),
        migrations.AddField(
            model_name='project',
            name='div',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
