# Generated by Django 5.1.4 on 2025-03-23 13:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_remove_currentsem_div_project_div'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.domain'),
        ),
    ]
