# Generated by Django 5.1.4 on 2025-03-23 17:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_project_domain'),
    ]

    operations = [
        migrations.CreateModel(
            name='DomainPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_students', to='api.domain')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferences', to='api.project')),
            ],
            options={
                'db_table': 'domain_preference',
                'unique_together': {('project', 'domain')},
            },
        ),
        migrations.CreateModel(
            name='GuidePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('preference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_preferences', to='api.domainpreference')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_students', to='api.teacher')),
            ],
            options={
                'db_table': 'guide_preference',
                'unique_together': {('preference', 'teacher')},
            },
        ),
    ]
