# Generated by Django 5.1.4 on 2025-03-30 03:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_domainpreference_guidepreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectGuide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_group', models.IntegerField()),
                ('guides', models.ManyToManyField(to='api.teacher')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sem')),
            ],
        ),
    ]
