# Generated by Django 5.1.4 on 2025-03-30 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_projectguide'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectguide',
            name='guides',
        ),
        migrations.RemoveField(
            model_name='projectguide',
            name='max_group',
        ),
        migrations.AddField(
            model_name='projectguide',
            name='availability',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='projectguide',
            name='teacher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
    ]
