# Generated by Django 5.1.4 on 2025-03-31 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_remove_projectguide_guides_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sem',
            name='form',
        ),
        migrations.AddField(
            model_name='sem',
            name='student_form',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sem',
            name='teacher_form',
            field=models.IntegerField(default=0),
        ),
    ]
