# Generated by Django 5.1.4 on 2025-04-01 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_sem_form_sem_student_form_sem_teacher_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectguide',
            name='form',
            field=models.IntegerField(default=0),
        ),
    ]
