# Generated by Django 5.1.4 on 2025-04-01 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_projectguide_form'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='final',
            field=models.IntegerField(default=0),
        ),
    ]
