# Generated by Django 5.1.4 on 2025-04-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_project_final'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='shortform',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
