# Generated by Django 5.1.4 on 2025-04-05 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_department_shortform'),
    ]

    operations = [
        migrations.CreateModel(
            name='Week',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveIntegerField()),
                ('sem', models.CharField(choices=[('sem_7', 'Semester 7'), ('sem_8', 'Semester 8')], max_length=5, null=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='api.sem')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=255)),
                ('sequence_number', models.PositiveIntegerField()),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.week')),
            ],
            options={
                'ordering': ['sequence_number'],
                'unique_together': {('week', 'sequence_number')},
            },
        ),
    ]
