# Generated by Django 5.1.4 on 2025-04-06 10:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_week_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('filing_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copyrights', to='api.project')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sem')),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255)),
                ('filing_date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=100)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patents', to='api.project')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sem')),
            ],
        ),
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_name', models.CharField(max_length=255)),
                ('conference_date', models.DateField()),
                ('conference_name', models.CharField(max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publications', to='api.project')),
                ('sem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sem')),
            ],
        ),
    ]
