# Generated by Django 5.1.4 on 2025-04-07 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_assessmentevent_assessmentpanel_unassignedgroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessmentpanel',
            name='teachers',
            field=models.ManyToManyField(related_name='assessment_panels', to='api.teacher'),
        ),
        migrations.AlterField(
            model_name='unassignedteacher',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.teacher'),
        ),
    ]
