# Generated by Django 5.1.4 on 2025-04-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_alter_assessmentpanel_teachers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='group_no',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
