# Generated by Django 5.1.4 on 2025-04-08 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_projectweekprogress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectweekprogress',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
    ]
