# Generated by Django 5.1.4 on 2025-04-20 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_projectweekprogress_is_final'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='year',
            unique_together={('department', 'year')},
        ),
    ]
