# Generated by Django 5.1.4 on 2025-04-24 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_alter_year_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='task',
            unique_together=set(),
        ),
    ]
