# Generated by Django 5.1.4 on 2025-04-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_alter_task_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='week',
            unique_together={('semester', 'week_number', 'sem')},
        ),
    ]
