# Generated by Django 5.1.4 on 2025-04-27 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_alter_projectweekprogress_submitted_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniProjectGuidePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prfered_guides', to='api.teacher')),
            ],
            options={
                'db_table': 'mini_guide_preference',
            },
        ),
    ]
