# Generated by Django 5.1.4 on 2025-04-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_miniprojectguidepreference'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MiniProjectGuidePreference',
        ),
    ]
