# Generated by Django 5.1.4 on 2025-04-27 17:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_delete_miniprojectguidepreference'),
    ]

    operations = [
        migrations.CreateModel(
            name='MiniProjectGuidePreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.IntegerField()),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_preferences', to='api.project')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preferred_guide', to='api.teacher')),
            ],
            options={
                'db_table': 'mini_guide_preference',
            },
        ),
    ]
