# Generated by Django 5.1.4 on 2025-04-28 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_miniprojectguidepreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectguide',
            name='max_groups',
            field=models.IntegerField(default=0),
        ),
    ]
