# Generated by Django 5.1.4 on 2025-05-08 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0043_assessmentrubric'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assessments', to='api.assessmentevent')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='project_assessments', to='api.project')),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentMark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marks', models.PositiveIntegerField()),
                ('rubric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.assessmentrubric')),
                ('project_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='api.projectassessment')),
            ],
        ),
    ]
