# Generated by Django 5.1.4 on 2025-05-29 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0045_link_linkupload_upload'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Upload',
            new_name='Resource',
        ),
    ]
