# Generated by Django 5.1.4 on 2025-05-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0047_linkupload_project_alter_linkupload_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
