# Generated by Django 5.1.4 on 2025-06-01 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0048_teacher_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagementPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tecaher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='access', to='api.teacher')),
            ],
        ),
    ]
