# Generated by Django 5.1.4 on 2025-06-01 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0049_managementpermission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='managementpermission',
            old_name='tecaher',
            new_name='teacher',
        ),
    ]
