# Generated by Django 5.1.4 on 2025-06-04 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0050_rename_tecaher_managementpermission_teacher'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='teacherpreference',
            table='TeacherPreference',
        ),
    ]
