# Generated by Django 5.1.4 on 2025-06-04 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0051_alter_teacherpreference_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='assessmentevent',
            table='AssessmentEvent',
        ),
        migrations.AlterModelTable(
            name='assessmentmark',
            table='AssessmentMark',
        ),
        migrations.AlterModelTable(
            name='assessmentpanel',
            table='AssessmentPanel',
        ),
        migrations.AlterModelTable(
            name='assessmentrubric',
            table='AssessmentRubric',
        ),
        migrations.AlterModelTable(
            name='copyright',
            table='Copyright',
        ),
        migrations.AlterModelTable(
            name='link',
            table='Link',
        ),
        migrations.AlterModelTable(
            name='linkupload',
            table='LinkUpload',
        ),
        migrations.AlterModelTable(
            name='managementpermission',
            table='ManagementPermission',
        ),
        migrations.AlterModelTable(
            name='patent',
            table='Patent',
        ),
        migrations.AlterModelTable(
            name='projectassessment',
            table='ProjectAssessment',
        ),
        migrations.AlterModelTable(
            name='projectguide',
            table='ProjectGuide',
        ),
        migrations.AlterModelTable(
            name='projecttask',
            table='ProjectTask',
        ),
        migrations.AlterModelTable(
            name='projectweekprogress',
            table='ProjectWeekProgress',
        ),
        migrations.AlterModelTable(
            name='publication',
            table='Publication',
        ),
        migrations.AlterModelTable(
            name='resource',
            table='Resource',
        ),
        migrations.AlterModelTable(
            name='task',
            table='task',
        ),
        migrations.AlterModelTable(
            name='unassignedgroup',
            table='UnassignedGroup',
        ),
        migrations.AlterModelTable(
            name='unassignedteacher',
            table='UnassignedTeacher',
        ),
        migrations.AlterModelTable(
            name='week',
            table='week',
        ),
    ]
