# Generated by Django 5.2.3 on 2025-07-17 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0052_alter_assessmentevent_table_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='form',
            field=models.IntegerField(default=0),
        ),
    ]
