from django.contrib import admin
from .models import *
# Register your models here.
admin.site.register(Department)
admin.site.register(Designation)
admin.site.register(Teacher)
admin.site.register(Year)
admin.site.register(Batch)
admin.site.register(Student)
admin.site.register(Domain)
admin.site.register(TeacherPreference)
admin.site.register(Sem)
admin.site.register(Project)
admin.site.register(CurrentSem)
admin.site.register(Notification)
admin.site.register(DomainPreference)
admin.site.register(GuidePreference)
admin.site.register(MiniProjectGuidePreference)
admin.site.register(ProjectGuide)
admin.site.register(Week)
admin.site.register(Task)
admin.site.register(Publication)
admin.site.register(Copyright)
admin.site.register(Patent)
admin.site.register(AssessmentEvent)
admin.site.register(AssessmentPanel)
admin.site.register(UnassignedTeacher)
admin.site.register(UnassignedGroup)
admin.site.register(ProjectTask)
admin.site.register(ProjectWeekProgress)
admin.site.register(AssessmentRubric)
admin.site.register(ProjectAssessment)
admin.site.register(AssessmentMark)
admin.site.register(Resource)
admin.site.register(Link)
admin.site.register(LinkUpload)
admin.site.register(ManagementPermission)